In [2]:
from sklearn.linear_model import LinearRegression
import pandas as pd
import numpy as np

In [3]:
dataset = pd.read_csv("SaratogaHouses.csv")

In [6]:
X = dataset['livingArea'].values
y =dataset ['price'].values

In [8]:
X[:10]

array([ 906, 1953, 1944, 1944,  840, 1152, 2752, 1662, 1632, 1416],
      dtype=int64)

In [10]:
X = X.reshape(-1,1)

In [11]:
reg = LinearRegression()
reg.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [12]:
y_pred = reg.predict(X)

In [13]:
print(y[:10])
print(y_pred[:10])

[132500 181115 109000 155000  86060 120000 153000 170000  90000 122900]
[115928.4169181  234367.71823171 233349.61535509 233349.61535509
 108462.32915621 143756.56221241 324752.62916731 201449.05855429
 198055.38229888 173620.91325997]


In [14]:
from sklearn.model_selection import train_test_split

In [16]:
x_train, x_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [18]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1382L, 1L)
(1382L,)
(346L, 1L)
(346L,)


In [19]:
print(X.shape)
print(y.shape)

(1728L, 1L)
(1728L,)


In [20]:
reg_2 = LinearRegression()
reg_2.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [21]:
y_pred = reg_2.predict(x_test)

In [22]:
print(y_pred)

[274562.94455299 225625.02728013 182748.22820162 132014.42405636
 120116.67352672 224390.35505536 160075.15643758 222482.22525343
 193972.52115411 310256.19614191 149973.29278034 254246.97430898
 165687.30291383 173095.33626247 202054.0120799  221808.76767628
 160524.12815568 143687.68872695 202951.9555161  237522.77780977
 188921.58932549 143014.2311498  117647.32907717 270185.47030152
 192176.63428171 204972.32824755 136504.14123735 325296.74869825
 181401.31304732 206094.7575428  191952.14842266 271195.65666724
 153565.06652514 248747.07076226 181401.31304732 190492.99033883
 133698.06799923 117647.32907717 114504.52705047 181401.31304732
 143238.71700885 168381.13322243 181401.31304732 219114.93736769
 148177.40590794 156258.89683374 131340.96647921 362336.91544147
 123034.98969436 297348.25924655 117647.32907717 200482.61106655
 184544.11507401 193186.82064743 136504.14123735 340786.27297269
 202278.49793895 181401.31304732 221584.28181723 169615.8054472
 203064.19844562 173319.82

In [23]:
from sklearn.metrics import mean_squared_error

In [24]:
mse = mean_squared_error(y_test,y_pred)

In [25]:
rmse = np.sqrt(mse)

In [27]:
print("ROOT MEAN SQUARE", rmse)

('ROOT MEAN SQUARE', 63686.643727607894)


In [28]:
from sklearn.preprocessing import StandardScaler

In [29]:
std = StandardScaler()

In [30]:
X = std.fit_transform(X)

C:\ProgramData\Anaconda2\lib\site-packages\sklearn\utils\validation.py:595: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [32]:
X[:10]

array([[-1.36985441],
       [ 0.31951971],
       [ 0.30499787],
       [ 0.30499787],
       [-1.47634791],
       [-0.9729241 ],
       [ 1.60873645],
       [-0.1500198 ],
       [-0.19842594],
       [-0.54695011]])

In [33]:
y = y.reshape(-1,1)

In [34]:
y = std.fit_transform(y)

In [35]:
y[:10]

array([[-0.80748259],
       [-0.31349249],
       [-1.04627242],
       [-0.57885403],
       [-1.27937193],
       [-0.93449845],
       [-0.59917657],
       [-0.42643499],
       [-1.23933653],
       [-0.90503077]])

In [36]:
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size=0.2)

In [37]:
reg_3 = LinearRegression()

In [38]:
reg_3.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [39]:
y_pred = reg_3.predict(x_test)

In [40]:
mse = mean_squared_error(y_test,y_pred)

In [41]:
rmse = np.sqrt(mse)

In [42]:
print(rmse)

0.6706674805953899


In [43]:
print(y_pred[:10])

[[-0.95412363]
 [ 0.72388363]
 [ 0.13929485]
 [ 0.56218886]
 [ 0.10876507]
 [ 0.04996697]
 [-0.63073409]
 [-0.09024388]
 [-0.72345417]
 [-0.89306407]]
